name: Bug report
description: Report a bug to help us improve
title: <system feature> <is not/does not> <expected behaviour>
labels: "bug,needs:triage"
projects: "NASA-PDS/6"
assignees: jordanpadams

body:
  - type: dropdown
    id: checked-for-duplicates
    attributes:
      label: Checked for duplicates
      description: Have you checked for duplicate issue tickets?
      multiple: false
      options:
        - "Yes - I've already checked"
        - "No - I haven't checked"
    validations:
      required: yes
  - type: textarea
    id: description
    attributes:
      label: 🐛 Describe the bug
      description: A clear and concise description of what the bug is. Plain-text snippets and/or screenshots welcome.
      placeholder: Tell us what you saw
      value: "When I did [...] action, I noticed [...]"
    validations:
      required: true
 
  - type: textarea
    id: expected-behavior
    attributes:
      label: 🕵️ Expected behavior
      description: A clear and concise description of what you expected to happen
      placeholder: Tell us what you expected
      value: "I expected [...]"
    validations:
      required: true
 
  - type: textarea
    id: reproduction
    attributes:
      label: 📜 To Reproduce
      description: "How would we reproduce this bug? Please walk us through it step by step. Plain-text snippets and/or screenshots welcome."
      value: |
        1.
        2.
        3.
        ...
 
  - type: textarea
    id: environment
    attributes:
      label: 🖥 Environment Info
      description: "What is your environment? Include any computer hardware, operating system, framework, browser, time-of-day or other contextual information related to your issue"
      value: |
        - Version of this software [e.g. vX.Y.Z]
        - Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
        ...

  - type: textarea
    id: version
    attributes:
      label: 📚 Version of Software Used
      description: Command-line tools should have a `-V` or `--version` flag to get this information.

  - type: textarea
    id: test_data
    attributes:
      label: 🩺 Test Data / Additional context
      description: "If not provided already, upload some test data. Note: May need to create a ZIP/TAR if the files are not compatible with GitHub."

  - type: textarea
    id: requirements
    attributes:
       label: 🦄 Related requirements
       description: If known, provide links to the requirements/user stories applicable to this bug.
       value: "🦄 #xyz"

  - type: markdown
    attributes:
      value: |
        ## For Internal Dev Team To Complete

  - type: textarea
    id: details
    attributes:
       label: ⚙️ Engineering Details

  - type: textarea
    id: i-n-t
    attributes:
      label: 🎉 Integration & Test
      description: To be filled out by Engineering Node Team
      placeholder:  Provide testing information and/or trace to TestRail ID
    validations:
      required: false
